apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapincrementors.qsahal.org
spec:
  scope: Namespaced
  group: qsahal.org
  names:
    kind: ConfigMapIncrementor
    plural: configmapincrementors
    singular: confimapincrementor
    shortNames:
      - cmi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            sign:
              type: string
          type: object
          x-kubernetes-preserve-unknown-fields: true
