apiVersion: v1
kind: Pod
metadata:
  name: "toolbox"
  labels:
    app: "toolbox"
spec:
  containers:
  - name: myapp
    image: "quentin1006/toolbox"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
      name: http
  restartPolicy: Always

# docker build -t localhost:5001/toolbox .
# docker push localhost:5001/toolbox
# docker run -d -p 5001:5000 --restart always --name registry registry:2
