apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  activeDeadlineSeconds: 3600
  containers:
    - name: debug-container
      image: docker.io/bitnami/postgresql:17.4.0-debian-12-r11 
      command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      volumeMounts:
        - name: backup-dir
          mountPath: /backup
  volumes:
    - name: backup-dir
      persistentVolumeClaim:
        claimName: postgresql-pgdumpall
  restartPolicy: Never