kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # necessary to map the host port to the kindest container port
  extraPortMappings:
  - containerPort: 80
    hostPort: 8090
    protocol: TCP
  - containerPort: 443
    hostPort: 44390
    protocol: TCP