# Basic app that uses a longhorn volume, a volume snpashot can be taken from it
# and then we can test the export with velero to another cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-deployment
  labels:
    app: longhorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn
  template:
    metadata:
      labels:
        app: longhorn
    spec:
      containers:
      - name: longhorn-container
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: longhorn-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: longhorn-volume
        persistentVolumeClaim:
          claimName: longhorn-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: longhorn-service
spec:
  selector:
    app: longhorn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

