# This YAML file demonstrates how to restore a PersistentVolumeClaim (PVC) from a VolumeSnapshot in Kubernetes using the HostPath CSI driver.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  dataSource:
    name: my-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: hostpath

---
apiVersion: v1
kind: Pod
metadata:
  name: restored-pvc-pod
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: restored-pvc-volume
  volumes:
    - name: restored-pvc-volume
      persistentVolumeClaim:
        claimName: restored-pvc