apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      # EDIT: Doesnt work because i cant configure containerd to fetch from http registries (insecure registries
      # So for now i will used image pushed to dockerhub
      # In order for this to work we have to connect the registry container to the kind container network
      # we have to hit port 5000 cause it is the port opened on the container and not on the host 
      # image: reg:5000/toolbox
      image: quentin1006/toolbox
      command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
  restartPolicy: Never