# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "busybox"
  namespace: default
  labels:
    app: "busybox"
spec:
  containers:
    - name: busybox
      image: "busybox:latest"
      command: ["sleep", "3600"]
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      # env:
      # - name: DB_HOST
      #   valueFrom:
      #     configMapKeyRef:
      #       name: myapp
      #       key: DB_HOST
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - name: mypvc-mount
          mountPath: /etc/foo
  volumes:
    - name: mypvc-mount
      persistentVolumeClaim:
        claimName: mypvc
---
