mode: standalone
auth:
  rootUser: minio
  rootPassword: password
persistence:
  enabled: true
  storageClass: standard
  size: 10Gi
apiIngress:
  enabled: true
  ingressClassName: nginx
  hostname: backup-storage.local
# ingress:
#   enabled: true
#   ingressClassName: nginx
#   hostname: backup-storage.local
provisioning:
  enabled: true
  extraCommands:
    - mc ls provisioning/velero || mc mb provisioning/velero