apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      image: localhost:5001/toolbox
      command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: backup-volume
          mountPath: /mnt/backup
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
  volumes:
    - name: backup-volume
      persistentVolumeClaim:
        claimName: backup-pvc
  restartPolicy: Never