apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.zalando.org
spec:
  scope: Namespaced
  group: zalando.org
  names:
    kind: Database
    plural: databases
    singular: database
    shortNames:
      - db
      - dbs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            dbType:
              type: string
          type: object
          x-kubernetes-preserve-unknown-fields: true